[tool.poetry]
name = "goiteenscertificatebot"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
pillow = "^9.5.0"
python-dotenv = "^1.0.0"
pytelegrambotapi = "^4.12.0"
uvloop = "^0.17.0"
aiofiles = "^23.1.0"
aiohttp = "^3.8.4"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
